package com.dbviewer.app.sql;

import com.dbviewer.app.dto.ColumnInfo;
import com.dbviewer.app.dto.Relationship;

import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Writes a workspace back out as a script the chosen engine will actually run.
 *
 * <p>The export used to be SQLite's own {@code sqlite_master} DDL with the rows appended, which
 * is fine as long as the destination is also SQLite. It is not: the whole reason to draw a schema
 * is to build it somewhere, and the four lines that matter most —
 * {@code INTEGER PRIMARY KEY AUTOINCREMENT} versus {@code SERIAL} versus {@code IDENTITY(1,1)},
 * {@code "quoted"} versus {@code `quoted`} versus {@code [quoted]} — are exactly the ones no
 * other engine accepts. A script that is nearly right is worse than no script, because the error
 * arrives at the destination rather than here.
 *
 * <p>So nothing is copied through. The schema is rebuilt from introspected metadata in the target
 * engine's own vocabulary, tables are emitted parents-first so the foreign keys can be declared
 * inline rather than patched on afterwards, and every literal is escaped the way that engine
 * expects.
 */
public final class SqlExportWriter {

    /**
     * One table, as read back out of the workspace.
     *
     * @param autoIncrementColumns columns that generate their own value - a SQLite rowid alias,
     *                             which becomes SERIAL, IDENTITY or AUTO_INCREMENT on the way out
     */
    public record Table(String name,
                        List<ColumnInfo> columns,
                        List<Relationship> foreignKeys,
                        List<Map<String, Object>> rows,
                        Set<String> autoIncrementColumns) {
    }

    /** Beyond this a dump stops being something anyone opens in an editor. */
    private static final int MAX_ROWS_PER_TABLE = 100_000;

    private SqlExportWriter() {
    }

    public static String write(List<Table> tables, SqlDialect target) {
        StringBuilder out = new StringBuilder();
        List<Table> ordered = parentsFirst(tables);

        out.append("-- Schema export generated by SQL Visualizer\n");
        out.append("-- Target dialect: ").append(target.label()).append('\n');
        out.append("-- Tables: ").append(ordered.size()).append("\n\n");

        if (target.isMysqlFamily()) {
            out.append("SET FOREIGN_KEY_CHECKS = 0;\n\n");
        }

        // Dropped in reverse so a child never outlives the parent it points at.
        for (int i = ordered.size() - 1; i >= 0; i--) {
            out.append(dropStatement(ordered.get(i).name(), target));
        }
        out.append('\n');

        for (Table table : ordered) {
            out.append(createStatement(table, target));
            out.append(insertStatements(table, target));
        }

        if (target.isMysqlFamily()) {
            out.append("SET FOREIGN_KEY_CHECKS = 1;\n");
        }

        return out.toString();
    }

    /* ── DDL ─────────────────────────────────────────────────────────────────── */

    private static String dropStatement(String table, SqlDialect target) {
        String statement = target == SqlDialect.SQLSERVER
                // SQL Server only learned DROP TABLE IF EXISTS in 2016; the catalogue check runs
                // everywhere.
                ? "IF OBJECT_ID('" + escape(table, target) + "', 'U') IS NOT NULL DROP TABLE "
                        + target.quote(table) + ";"
                : "DROP TABLE IF EXISTS " + target.quote(table) + ";";
        return statement + batchSeparator(target);
    }

    private static String createStatement(Table table, SqlDialect target) {
        List<String> definitions = new ArrayList<>();
        List<String> primaryKeys = table.columns().stream()
                .filter(ColumnInfo::isPk)
                .map(ColumnInfo::getName)
                .toList();

        // A single auto-incrementing key is declared on the column itself on every engine, and
        // only there: no engine accepts SERIAL or IDENTITY in a table-level constraint.
        String inlineKeyColumn = primaryKeys.size() == 1
                && table.autoIncrementColumns().contains(primaryKeys.get(0))
                ? primaryKeys.get(0)
                : null;

        for (ColumnInfo column : table.columns()) {
            StringBuilder def = new StringBuilder("  ").append(target.quote(column.getName())).append(' ');

            if (column.getName().equals(inlineKeyColumn)) {
                def.append(SqlTypeMapper.autoIncrementPrimaryKey(target));
            } else {
                def.append(SqlTypeMapper.fromSqlite(column.getType(), target));
                if (column.isNotNull() || column.isPk()) {
                    def.append(" NOT NULL");
                }
            }
            definitions.add(def.toString());
        }

        if (inlineKeyColumn == null && !primaryKeys.isEmpty()) {
            definitions.add("  PRIMARY KEY (" + join(primaryKeys, target) + ")");
        }

        // Composite foreign keys arrive one row per column pair, so they are grouped back
        // together by the table they point at before being rendered.
        Map<String, List<Relationship>> grouped = new LinkedHashMap<>();
        for (Relationship fk : table.foreignKeys()) {
            grouped.computeIfAbsent(fk.getTargetTable(), k -> new ArrayList<>()).add(fk);
        }
        grouped.forEach((targetTable, group) -> definitions.add(
                "  FOREIGN KEY (" + join(group.stream().map(Relationship::getSourceColumn).toList(), target)
                        + ") REFERENCES " + target.quote(targetTable)
                        + " (" + join(group.stream().map(Relationship::getTargetColumn).toList(), target) + ")"));

        return "-- " + table.name() + '\n'
                + "CREATE TABLE " + target.quote(table.name()) + " (\n"
                + String.join(",\n", definitions)
                + "\n);" + batchSeparator(target);
    }

    /* ── Data ────────────────────────────────────────────────────────────────── */

    private static String insertStatements(Table table, SqlDialect target) {
        if (table.rows().isEmpty()) {
            return "\n";
        }

        StringBuilder out = new StringBuilder();
        List<String> columns = new ArrayList<>(table.rows().get(0).keySet());
        Map<String, ColumnInfo> byName = new LinkedHashMap<>();
        table.columns().forEach(c -> byName.put(c.getName(), c));

        // The rows carry the ids they already have, because a foreign key in the next table
        // refers to them. Handing an explicit value to a generated column is a hard error on
        // SQL Server unless it is asked for first.
        String identityColumn = columns.stream()
                .filter(c -> table.autoIncrementColumns().contains(c))
                .findFirst()
                .orElse(null);
        boolean guardIdentity = identityColumn != null && target == SqlDialect.SQLSERVER;
        if (guardIdentity) {
            out.append("SET IDENTITY_INSERT ").append(target.quote(table.name())).append(" ON;\n");
        }

        String prefix = "INSERT INTO " + target.quote(table.name())
                + " (" + join(columns, target) + ") VALUES ";

        int written = 0;
        for (Map<String, Object> row : table.rows()) {
            if (written++ >= MAX_ROWS_PER_TABLE) {
                out.append("-- ").append(table.rows().size() - MAX_ROWS_PER_TABLE)
                        .append(" further row(s) omitted from this export.\n");
                break;
            }
            List<String> values = columns.stream()
                    .map(c -> literal(row.get(c), byName.get(c), target))
                    .toList();
            out.append(prefix).append('(').append(String.join(", ", values)).append(");\n");
        }

        if (guardIdentity) {
            out.append("SET IDENTITY_INSERT ").append(target.quote(table.name())).append(" OFF;\n");
        }

        // PostgreSQL's sequence does not know that rows were inserted with ids already in them,
        // so the very next INSERT the user runs would collide on the primary key. This is the
        // difference between a script that loads and a database that works afterwards.
        if (identityColumn != null && target == SqlDialect.POSTGRES) {
            out.append("SELECT setval(pg_get_serial_sequence('")
                    .append(escape(table.name(), target)).append("', '")
                    .append(escape(identityColumn, target)).append("'), ")
                    .append("COALESCE((SELECT MAX(").append(target.quote(identityColumn))
                    .append(") FROM ").append(target.quote(table.name())).append("), 1), true);\n");
        }

        return out.append(batchSeparator(target)).toString();
    }

    /**
     * Renders one value as a literal the target engine will accept.
     *
     * <p>Booleans are the interesting case: PostgreSQL wants {@code TRUE}, everything else wants
     * {@code 1}, and SQLite stored it as an integer either way — so the column's declared type is
     * what says which of those a 1 actually means.
     */
    private static String literal(Object value, ColumnInfo column, SqlDialect target) {
        if (value == null) {
            return "NULL";
        }
        boolean isBoolean = column != null && column.getType() != null
                && column.getType().toUpperCase(Locale.ROOT).startsWith("BOOL");

        if (isBoolean && target == SqlDialect.POSTGRES) {
            return truthy(value) ? "TRUE" : "FALSE";
        }
        if (value instanceof Boolean flag) {
            return flag ? "1" : "0";
        }
        if (value instanceof Number number) {
            return number.toString();
        }
        if (value instanceof byte[]) {
            return "NULL"; // Binary has no portable literal form; the column keeps its shape.
        }
        return "'" + escape(value.toString(), target) + "'";
    }

    private static boolean truthy(Object value) {
        if (value instanceof Boolean flag) return flag;
        if (value instanceof Number number) return number.intValue() != 0;
        String text = value.toString().trim();
        return text.equalsIgnoreCase("true") || text.equals("1") || text.equalsIgnoreCase("yes");
    }

    /**
     * Escapes a string literal.
     *
     * <p>Doubling the quote is universal. The backslash is not: MySQL and MariaDB treat it as an
     * escape character inside literals by default, so a Windows path or a regex in the data
     * silently changes meaning unless it is doubled as well.
     */
    private static String escape(String value, SqlDialect target) {
        String escaped = value.replace("'", "''");
        if (target.isMysqlFamily()) {
            escaped = escaped.replace("\\", "\\\\");
        }
        return escaped;
    }

    /* ── Layout ──────────────────────────────────────────────────────────────── */

    /** SQL Server scripts are run as batches; everything else just gets a blank line. */
    private static String batchSeparator(SqlDialect target) {
        return target == SqlDialect.SQLSERVER ? "\nGO\n" : "\n";
    }

    private static String join(Collection<String> identifiers, SqlDialect target) {
        return String.join(", ", identifiers.stream().map(target::quote).toList());
    }

    /**
     * Orders tables so a table is emitted after everything it references.
     *
     * <p>Without it the export only loads cleanly on an engine that defers constraint checking,
     * and the user finds out by watching it fail halfway. A cycle (two tables referencing each
     * other) has no valid order at all, so the remaining tables are appended in their original
     * order rather than the sort throwing.
     */
    private static List<Table> parentsFirst(List<Table> tables) {
        Map<String, Table> byName = new LinkedHashMap<>();
        tables.forEach(t -> byName.put(t.name(), t));

        List<Table> ordered = new ArrayList<>();
        Set<String> placed = new LinkedHashSet<>();
        Set<String> visiting = new LinkedHashSet<>();

        for (Table table : tables) {
            place(table, byName, ordered, placed, visiting);
        }
        return ordered;
    }

    private static void place(Table table, Map<String, Table> byName, List<Table> ordered,
                              Set<String> placed, Set<String> visiting) {
        if (placed.contains(table.name()) || !visiting.add(table.name())) {
            return; // Already emitted, or we are inside a cycle and must stop unwinding it.
        }
        for (Relationship fk : table.foreignKeys()) {
            Table parent = byName.get(fk.getTargetTable());
            if (parent != null && !parent.name().equals(table.name())) {
                place(parent, byName, ordered, placed, visiting);
            }
        }
        visiting.remove(table.name());
        if (placed.add(table.name())) {
            ordered.add(table);
        }
    }
}
